# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  poolname: '$(Build.BuildId)'
  URI: 'https://dev.azure.com/bansalpreeti1'
  projectname: 'k8'
  sharedSecret: 'sharedsecret1234'
  targetSize: '1'

stages:
- stage: Cleanup_test_rsources 
  jobs:

  ################################################################################
  - job: Clean_resources_created_for_test
  ################################################################################
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      
      - task: HelmInstaller@1
        inputs:
          helmVersionToInstall: 'latest'

      - task: HelmDeploy@0
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
          azureResourceGroup: 'processmonitor-rg'
          kubernetesCluster: 'testop'
          command: 'ls'