# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  poolname: '$(Build.BuildId)'
  URI: 'https://dev.azure.com/bansalpreeti1'
  projectname: 'k8'
  sharedSecret: 'sharedsecret1234'
  targetSize: '1'

stages:
- stage: Cleanup_test_rsources 
  jobs:

  ################################################################################
  - job: Clean_resources_created_for_test
  ################################################################################
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
      
            Write-Host "Hello World"
            
            $header = @{
              "Accept"="application/json"
              "Authorization"="Basic OmprbGFnNXFoaWR4djRxcGc1dGJoMnZoa3RvdXFhaGlseG5meHhscW15dDd3cTRreHRkemE="
              "Content-Type"="application/json"
             } 
         
             $response2 = Invoke-WebRequest -Uri "$(URI)/$(projectname)/_settings/agentqueues?__rt=fps&__ver=2" -Method 'Get'  -Headers $header
        
             Write-Host $response2
        
             $queuejsonObj = ConvertFrom-Json $([String]::new($response2.Content))
        
             $queueId = $queuejsonObj.fps.dataProviders.data.'ms.vss-build-web.agent-queues-data-provider'.taskAgentQueues.Where({$_.name -eq 1115}).id
        
             Write-Host "QueueId is ". $queueId
             $url = "$(URI)/$(projectname)/_apis/distributedtask/queues/$($queueId)?api-version=5.0-preview"
            
             Write-Host "Delete url is ". $url
             $response = Invoke-WebRequest -Uri $url -Method 'Delete' -Headers $header
            
             Write-Host $response
             Write-Host 'Deleted Agent Pool'

      - task: HelmInstaller@1
        inputs:
          helmVersionToInstall: 'latest'

      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'k8_l2testcase'
          namespace: 'default'
          command: 'delete'
          arguments: 'azurepipelinespool azurepipelinespool-operator'
      - task: HelmDeploy@0
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
          azureResourceGroup: 'processmonitor-rg'
          kubernetesCluster: 'testop'
          command: 'delete'
          arguments: 'release-1115'

      - task: HelmDeploy@0
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
          azureResourceGroup: 'processmonitor-rg'
          kubernetesCluster: 'testop'
          command: 'ls'