# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-cg1

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'prebansa_docker'
    repository: 'prebansa/myagent'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'LogOnly'
    verbosity: 'Verbose'
    dockerImagesToScan: 'prebansa/myagent:$(Build.BuildId)'
    alertWarningLevel: 'Medium'
