# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- users/prebansa/httpssupport

variables:
  poolname: '$(Build.BuildId)'
  URI: 'https://dev.azure.com/bansalpreeti1'
  projectname: 'k8'
  targetSize: '1'

stages:
- stage: Deploy_Pool_Provider_Agent
  jobs:

  ################################################################################
  - job: Configure_poolprovider
  ################################################################################
    pool:
      vmImage: 'ubuntu-latest'

    steps:

      - task: HelmInstaller@1
        inputs:
          helmVersionToInstall: 'latest'
      - task: HelmDeploy@0
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
          azureResourceGroup: 'processmonitor-rg'
          kubernetesCluster: 'httpsaks'
          command: 'init'
          upgradeTiller: false
          waitForExecution: false
      - task: AzureCLI@1
        inputs:
          azureSubscription: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az aks get-credentials --name httpsaks --resource-group processmonitor-rg
            
            fqdn="azurepipelinespooltest.southindia.cloudapp.azure.com"
            
            echo $fqdn
            
            # Install the CustomResourceDefinition resources separately
            kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.8/deploy/manifests/00-crds.yaml
            
            # Add the Jetstack Helm repository
            helm repo add jetstack https://charts.jetstack.io
            
            # Update your local Helm chart repository cache
            helm repo update
            
            # Install the cert-manager Helm chart
            helm install --name-template cert-manager --namespace cert-manager --version v0.8.0 jetstack/cert-manager
            
            sleep 70
            
            helm install helm/k8s-certmanager --name-template='releasecert-$(Build.BuildId)' --set 'configvalues.dnsname=$fqdn'