# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  poolname: '$(Build.BuildId)'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks get-credentials --name aksKodey --resource-group aksKodey'
      
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: '3.0.3'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd helm
      
      ./setup.sh -u true -s sharedsecret1234 -d azure$(poolname)

