version: '2'

services:
  redis:
    image: redis:3-alpine
  simple-webserver:
    image: divyanshm/goserver:v1.2
    command: -redis "redis:6379"
    depends_on:
      - redis
    links:
      - redis
    ports:
      - "8082:8082"
