# Need to create the opaque secret vsts once in namespace azuredevops before running this app.
# kubectl create secret generic vsts --from-literal=VSTS_TOKEN=<PAT TOKEN> --from-literal=VSTS_ACCOUNT=<Account name>  --from-literal=VSTS_POOL=<Pool name> -n azuredevops
apiVersion: v1
kind: Namespace
metadata:
  name: azuredevops
  labels:
    app: k8s-poolprovider
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: defaultrole-binding
  namespace: azuredevops
subjects:
  - kind: ServiceAccount
    name: default
    namespace: azuredevops
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-poolprovider
  namespace: azuredevops
  labels:
    app: k8s-poolprovider
spec:
  type: LoadBalancer
  ports:
    - port: 8082
  selector:
    app: k8s-poolprovider
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-poolprovider
  namespace: azuredevops
  labels:
    app: k8s-poolprovider
spec:
  template:
    metadata:
      labels:
        app: k8s-poolprovider
        tier: frontend
    spec:
      containers:
      - image: divyanshm/k8s-poolprovider:v2.18
        name: k8s-poolprovider
        command: ["/app/main"]
        ports:
        - containerPort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-poolprovider
  namespace: azuredevops
  labels:
    app: k8s-poolprovider
spec:
  backend:
    serviceName: k8s-poolprovider
    servicePort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-poolprovider-redis
  namespace: azuredevops
  labels:
    app: k8s-poolprovider
spec:
  ports:
    - port: 6379
  selector:
    app: k8s-poolprovider
    tier: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-poolprovider-redis
  namespace: azuredevops
  labels:
    app: k8s-poolprovider
spec:
  template:
    metadata:
      labels:
        app: k8s-poolprovider
        tier: redis
    spec:
      containers:
      - image: redis:3-alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis