apiVersion: v1
kind: Namespace
metadata:
  name: azuredevops
  labels:
    app: goserver
---
apiVersion: v1
kind: serviceAccount
metadata: 
  name: pipelineprovider
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: azuredevops-pipelineprovider
subjects:
  - kind: ServiceAccount
    name: pipelineprovider
    namespace: azuredevops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: goserver
  labels:
    app: goserver
  namespace: azuredevops
spec:
  type: NodePort
  ports:
    - port: 8082
  selector:
    app: goserver
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
  namespace: azuredevops
spec:
  template:
    metadata:
      labels:
        app: goserver
        tier: frontend
    spec:
      serviceAccountName: pipelineprovider
      containers:
      - image: divyanshm/goserver:v1.27
        name: goserver
        command: ["/app/main"]
        ports:
        - containerPort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: goserver
  name: goserver
  namespace: azuredevops
spec:
  backend:
    serviceName: goserver
    servicePort: 8082