apiVersion: v1
kind: Service
metadata:
  name: goserver
  labels:
    app: goserver
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8082
  selector:
    app: goserver
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  template:
    metadata:
      labels:
        app: goserver
        tier: frontend
    spec:
      containers:
      - image: divyanshm/goserver:v1.23
        name: goserver
        command: ["/app/main"]
        ports:
        - containerPort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: goserver
  name: goserver
  namespace: default
spec:
  backend:
    serviceName: goserver
    servicePort: 8082
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: goserver
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin # this is a hack, needs proper role assignments
  apiGroup: rbac.authorization.k8s.io