apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-poolprovider
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-poolprovider
  template:
    metadata:
      labels:
        name: k8s-poolprovider
    spec:
      serviceAccountName: k8s-poolprovider
      containers:
        - name: k8s-poolprovider
          # Replace this with the built image name
          image: prebansa/testbuildctl:v4.3
          command:
          - k8s-poolprovider
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k8s-poolprovider"
