kind: Secret
apiVersion: v1
metadata:
  name: azurepipelines
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  VSTS_SECRET: {{ .Values.vsts.VSTS_SECRET | b64enc }}