apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: operator-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - demo.k8s.com
  resources:
  - podconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete