apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podconfigs.demo.k8s.com
  namespace: azuredevops
spec:
  group: demo.k8s.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: podconfigs
    singular: podconfig
    kind: PodConfig