apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: buildkitd
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  serviceName: buildkitd
  replicas: {{ .Values.config.buildkitPodCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        role: buildkit
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
        container.seccomp.security.alpha.kubernetes.io/buildkitd: unconfined
# see buildkit/docs/rootless.md for caveats of rootless mode
    spec:
      containers:
      - name: buildkitd
        image: {{ .Values.config.buildkitImage }}
        args:
        - --addr
        - unix:///run/user/1000/buildkit/buildkitd.sock
        - --addr
        - tcp://0.0.0.0:1234
        - --oci-worker-no-process-sandbox
        ports:
        - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:  
  name: buildkitd
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  ports:
  - port: 1234
    protocol: TCP
  selector:
    app: {{ .Values.app.name }}