apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        tier: frontend
    spec:
      serviceAccountName: {{ .Values.rbac.name }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.app.name }}
        command: ["/app/main"]
        ports:
        - containerPort: 8080