kind: Secret
apiVersion: v1
metadata:
  name: vsts
  namespace: azuredevops
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  VSTS_ACCOUNT: {{ .Values.vsts.VSTS_ACCOUNT | b64enc }}
  VSTS_TOKEN: {{ .Values.vsts.VSTS_TOKEN | b64enc }}
  VSTS_POOL: {{ .Values.vsts.VSTS_POOL | b64enc }}
  VSTS_SECRET: {{ .Values.vsts.VSTS_SECRET | b64enc }}