apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    identifier: k8loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 8082
  selector:
    app: {{ .Values.app.name }}
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  backend:
    serviceName: {{ .Values.app.name }}
    servicePort: 8082