apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: {{ .Values.app.name }}
    tier: frontend