apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: defaultrole-binding
  namespace: azuredevops
subjects:
  - kind: ServiceAccount
    name: default
    namespace: azuredevops
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io