kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-poolprovider
  namespace: azuredevops
subjects:
- kind: ServiceAccount
  name: k8s-poolprovider
roleRef:
  kind: Role
  name: k8s-poolprovider
  apiGroup: rbac.authorization.k8s.io
