apiVersion: v1
kind: Pod
metadata:
    generateName: vsts-agent-sock-
spec:
  containers:
  - name: vsts-agent
    image: microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard
    env:
    - name: VSTS_ACCOUNT
      valueFrom:
        secretKeyRef:
          name: vsts
          key: VSTS_ACCOUNT
    - name: VSTS_TOKEN
      valueFrom:
        secretKeyRef:
          name: vsts
          key: VSTS_TOKEN
    - name: VSTS_POOL
      value: divman
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-volume
  volumes:
  - name: docker-volume
    hostPath: 
       path: /var/run/docker.sock 