apiVersion: v1
kind: Pod
metadata:
    generateName: vsts-agent-
spec:
  containers:
  - name: vsts-agent
    image: prebansa/myagent:v5.16
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    - name: RUNNING_ON
      valueFrom:
        configMapKeyRef:
          name: kubernetes-config
          key: type
    volumeMounts:
    - name: agent-creds
      mountPath: "/vsts/agent"
      readOnly: true