apiVersion: v1
kind: Pod
metadata:
    generateName: vsts-agent-
spec:
  containers:
  - name: vsts-agent
    image: divyanshm/agent:v1.0
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    volumeMounts:
    - name: agent-creds
      mountPath: "/vsts/agent"
      readOnly: true
  - name: dind-daemon
    image: docker:18.09.6-dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: agent-pv-storage
      mountPath: /var/lib/docker
  volumes:
  - name: agent-pv-storage
    emptyDir: {}